name: artiq
description: Artiq

version: 1.0.14+16

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^0.4.4+3
  firebase_analytics: ^5.0.11
  sqflite:
  path:

  cupertino_icons: ^0.1.2
  http: ^0.12.0+4
  cached_network_image: ^2.0.0
  dots_indicator: ^1.0.0
  flutter_email_sender: ^2.2.2
  flutter_youtube_view: ^1.1.8
  google_fonts: ^0.3.10
  easy_localization: ^2.1.0+0
  conreality_headset: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - res/languages/
  fonts:
    - family: UTOIMAGE
      fonts:
        - asset: res/fonts/UTOIMAGE.ttf